#!/bin/sh

scriptDir=$(dirname -- "$0")
[ "$scriptDir" = "." ] && readonly scriptDir=$(dirname -- $(which -- "$0")) || readonly scriptDir=$(cd "$scriptDir" && echo "${PWD}") || { echo >&2 "ERROR: Cannot determine absolute script dirspec!"; exit 1; }
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 1; }

testdir="${TMPDIR:-/tmp}/WriteBackupTest"
[ -d "$testdir" ] && { rm -rf "$testdir" || exit 1; }

# Note: The zip archive automatically preserves file timestamps for correct
# :WriteBackupListVersions output.
unzip "${scriptDir}/testdata.zip" -d "$testdir"
